services:
  db:
    image: mariadb:10.5.8
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: word@press
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: abc@123

  wordpress:
    depends_on:
      - db
    image: wordpress:6-php8.4
    container_name: wp
    volumes:
      - ./src:/var/www/html/wp-content/themes/dres-theme
      - ./dres-user-custom-fields:/var/www/html/wp-content/plugins/dres-user-custom-fields
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: abc@123
      WORDPRESS_DEBUG: 1
volumes:
  mysql_data: